import "./globals.css";
import 'nprogress/nprogress.css';
import 'react-toastify/dist/ReactToastify.css';
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Providers from "@/libs/providers"
import LoaderProviders from "@/libs/loader-provider"
import Head from "next/head";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Head>
        <meta charSet={"UTF-8"} />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
       
      </Head>
        <body className={inter.className}>
            <LoaderProviders/>
          <div className="container mx-auto p-4">
           <Providers> {children}</Providers>
          </div>
          </body>
    </html>
  );
}
